### ISSUE TITLE
Question about where to store the instances

### ISSUE THREAD

**Issue by Hynn01** [dcmjs-org/dicomweb-server#40]
After using the command "find DATA_DIRECTORY -iname \*.dcm -print0 | xargs -0 -n25 dicomweb_client --url http://localhost:5985 store instances", where do the dcm files store? I want to understand how this work but I can't figure it out...

**Comment by pieper** [comment]
The dicom files are stored as attachments to the corresponding document in couchdb.

You can read about the design in the readme and here:
https://projectweek.na-mic.org/PW30_2019_GranCanaria/Projects/DICOMweb-CouchDB/

**Comment by Hynn01** [comment]
Thank you!
